[package]
name = "snake"
version = "0.1.0"
authors = ["Halfwhit <Halfwhit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.4.0", features = ["dynamic"] }
rand = "0.8.3"